name: CI

env:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: postgres

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  rubocop:
    name: rubocop
    runs-on: ubuntu-latest
    container: exponentiateam/eschooltul-ci
    steps:
      - uses: actions/checkout@v2
      - run: bundle install
      - run: bundle exec rubocop

  eslint:
    name: eslint
    runs-on: ubuntu-latest
    container: exponentiateam/eschooltul-ci
    steps:
    - uses: actions/checkout@v2
    - run: yarn install
    - run: yarn lint

  rspec:
    needs: [ rubocop ]
    runs-on: ubuntu-latest
    container: exponentiateam/eschooltul-ci
    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ env.POSTGRES_DB }}
    steps:
      - uses: actions/checkout@v2
      - name: Build and test with RSpec
        env:
          RAILS_ENV: test
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
        run: |
          bundle install --jobs 4 --retry 3
          cp config/database.github.yml config/database.yml
          bundle exec rails db:setup
          bundle exec rails assets:precompile
          bundle exec rspec

  cypress:
    needs: [rubocop, eslint]
    runs-on: ubuntu-latest
    container: exponentiateam/eschooltul-ci
    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ env.POSTGRES_DB }}
    steps:
      - uses: actions/checkout@v2
      - name: Build and test with Cypress
        env:
          RAILS_ENV: test
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
        run: |
          bundle install --jobs 4 --retry 3
          yarn install
          yarn run cypress install
          yarn run cypress verify
          cp config/database.github.yml config/database.yml
          bundle exec rails db:setup
          bundle exec rails assets:precompile
          yarn start-server-and-wait
          yarn cy:run

  deploy:
    needs: [rspec, cypress]
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          branch: 'main'
          git_remote_url: 'ssh://dokku@167.99.40.52:22/eschooltul'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
