name: CI

env:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: postgres

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  rubocop:
    name: rubocop
    runs-on: ubuntu-latest
    container: mapreal19/parse-doc-ci # TODO: create dockerfile for "eschooltul"
    steps:
      - uses: actions/checkout@v2
      - run: bundle install
      - run: bundle exec rubocop

  eslint:
    name: eslint
    runs-on: ubuntu-latest
    container: mapreal19/parse-doc-ci
    steps:
    - uses: actions/checkout@v2
    - run: yarn install
    - run: yarn lint

  rspec:
    needs: [ rubocop ]
    runs-on: ubuntu-latest
    container: mapreal19/parse-doc-ci
    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ env.POSTGRES_DB }}
          
    steps:
      - uses: actions/checkout@v2
      - name: Build and test with RSpec
        env:
          RAILS_ENV: test
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
        run: |
          bundle install --jobs 4 --retry 3
          cp config/database.github.yml config/database.yml
          bundle exec rails db:setup
          bundle exec rails assets:precompile
          bundle exec rspec
